import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import PlaceCard from "../components/PlaceCard";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { useState } from "react";
import CardSlider from "../features/CardSlider";
export default function Home() {
  const [count, setCount] = useState(0);
  const footerVariants = {
    out: {
      y: 600,
    },
    in: {
      y: 0,
      transition: {
        duration: 0.6,
        // The first child will appear AFTER the parrent has appeared on the screen
        delayChildren: 1.9,
        // The next sibling will appear 0.5s after the previous one
        staggerChildren: 0.9,
      },
    },
  };
  const childrenVariants = {
    out: {
      opacity: 0,
    },
    in: {
      opacity: 1,
    },
  };
  const snsVariants = {
    out: {
      opacity: 0,
      x: -50,
    },
    in: {
      opacity: 1,
      x: 0,
    },
  };
  return (
    <motion.div className=" h-full">
      <Head>
        <title>Tokyo Slider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/blue-tokyo.png" />
      </Head>
      <Header />
      <motion.div
        initial={{ scale: 0.7 }}
        animate={{
          scale: 1,
          transition: { ease: "easeInOut", duration: 1, delay: 0.2 },
        }}
        className="bg-heroImage flex   h-full bg-cover absolute -z-10  w-screen top-0 left-0  bg-blend-overlay bg-black bg-opacity-40 overflow-hidden "
      >
        <div className=" h-full w-full flex flex-col lg:justify-center pt-28 pb-10 lg:py-16 shadow-innerShadow">
          {/* Central section text + slider */}
          <div className="flex flex-col z-0 lg:flex-row lg:items-center relative 2xl:pl-60 lg:pl-32   flex-1  lg:pr-32 ">
            {/* main text */}
            <div className="space-y-4 text-center    lg:text-left lg:ml-11 lg:m-0 z-40 ">
              <h1 className="font-Aboreto font-extrabold text-white text-5xl md:text-[800%] lg:text-[600%] xl:text-[900%] 2xl:text-[1100%] wideScreen:text-[1500%]">
                Tokyo
              </h1>
              <p className="font-Aboreto font-extrabold text-white lg:text-3xl lg:ml-4 wideScreen:text-5xl">
                ...not so far away
              </p>
            </div>
            <div className=" flex flex-1 items-center justify-center  scale-[0.9]      sm:scale-[1] md:scale-[1.1] lg:absolute  lg:mr-0 lg:mt-0 lg:ml-0  lg:top-[26%]  lg:scale-[0.8] lg:right-0 xl:-right-0 xl:scale-[0.9] 2xl:scale-100 2xl:items-end  2xl:right-32 wideScreen:static wideScreen:scale-150 ">
              <CardSlider />
            </div>
          </div>
          {/* Footer */}
          <motion.div
            initial="out"
            animate="in"
            variants={footerVariants}
            className="text-white font-Montserrat flex lg:flex-row flex-col justify-center space-y-4 px-3 lg:space-x-6 items-center 2xl:pl-60 2xl:m-0 lg:mx-auto"
          >
            <motion.div
              variants={childrenVariants}
              className="  lg:text-start space-y-1 pb-4 border-b lg:space-y-2 lg:border-r   text-center border-white lg:pr-6  "
            >
              <h3 className="text-2xl font-semibold wideScreen:text-4xl">
                Culture Festival
              </h3>
              <p className="text-xs font-normal wideScreen:text-lg">
                09-12 Augustus
              </p>
            </motion.div>
            <motion.p
              variants={childrenVariants}
              className="text-xs lg:text-sm font-light lg:text-start text-center wideScreen:text-lg"
            >
              Japan is a country of festivals. Known as matsure in Japanese.
              <br />
              These events celebrate or commemorate the changing of the
              sessions.
            </motion.p>
            {/* SNS */}
            <motion.div
              variants={childrenVariants}
              transition={{
                duration: 0.6,

                // The next sibling will appear 0.5s after the previous one
                staggerChildren: 0.5,
              }}
              className="m-0 flex space-x-6  flex-1 justify-center items-center lg:items-end"
            >
              <motion.div
                whileHover={{ scale: 1.2 }}
                variants={snsVariants}
                className="h-8 w-8 cursor-pointer wideScreen:h-12 wideScreen:w-12  relative"
              >
                <Image
                  className=""
                  src="/assets/tiktok.svg"
                  alt="logo insta"
                  layout="fill"
                />
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.2 }}
                variants={snsVariants}
                className="h-8 w-8 cursor-pointer  wideScreen:h-12 wideScreen:w-12  relative"
              >
                <Image
                  className=""
                  src="/assets/insta.svg"
                  alt="logo facebook"
                  layout="fill"
                />{" "}
              </motion.div>

              <motion.div
                whileHover={{ scale: 1.2 }}
                variants={snsVariants}
                className="h-8 w-8 cursor-pointer wideScreen:h-12 wideScreen:w-12  relative"
              >
                <Image
                  className=""
                  src="/assets/ytb.svg"
                  alt="logo youtube"
                  layout="fill"
                />{" "}
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.2 }}
                variants={snsVariants}
                className="h-8 w-8 cursor-pointer wideScreen:h-12 wideScreen:w-12 relative"
              >
                <Image
                  className=""
                  src="/assets/fb.svg"
                  alt="logo twitter"
                  layout="fill"
                />
              </motion.div>
            </motion.div>
          </motion.div>
        </div>
      </motion.div>
    </motion.div>
  );
}
